version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
    openjdk_executor:
        docker:
            - image: cimg/openjdk:17.0.3-node
        environment:
            _JAVA_OPTIONS: "-Xmx4g"
            GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build_and_test:
    executor:
      name: node/default
    working_directory: /home/circleci/mms5-auth-service
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true
      - run: 
            name: "Build image"
            command: |
              cp src/main/resources/application.conf.example ./src/main/resources/application.conf
              docker build -t openmbee/mms5-auth-service:latest .
      - run:
            name: "Export docker image"
            command: |
              docker save -o mms5-auth-service.tar openmbee/mms5-auth-service:latest
      - persist_to_workspace:
            root: /home/circleci/
            paths:
              - mms5-auth-service/*

  deploy_snapshot:
      executor: openjdk_executor
      working_directory: /home/circleci/mms5-auth-service
      steps:
          - setup_remote_docker:
                docker_layer_caching: true
          - attach_workspace:
                at: ~/
          - run:
                name: Login to Dockerhub
                command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - run:
                name: Load docker image
                command: docker load -i mms5-auth-service.tar
          - run:
                name: Tag docker image
                command: docker tag openmbee/mms5-auth-service:latest openmbee/mms5-auth-service:${CIRCLE_BRANCH#*/}-SNAPSHOT
          - run:
                name: Deploy snapshot to Dockerhub
                command: docker push openmbee/mms5-auth-service:${CIRCLE_BRANCH#*/}-SNAPSHOT
  deploy_release:
      executor: openjdk_executor
      working_directory: /home/circleci/mms5-auth-service
      steps:
          - setup_remote_docker:
                docker_layer_caching: true
          - attach_workspace:
                at: ~/
          - run:
                name: Login to Dockerhub
                command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - run:
                name: Load docker image
                command: docker load -i mms5-auth-service.tar
          - run:
                name: Tag docker image
                command: docker tag openmbee/mms5-auth-service:latest openmbee/mms5-auth-service:${CIRCLE_TAG}
          - run:
                name: Deploy release to dockerhub
                command: docker push openmbee/mms5-auth-service:${CIRCLE_TAG}
          - run:
                name: Deploy release as latest to dockerhub
                command: docker push openmbee/mms5-auth-service:latest

workflows:
    version: 2
    build-test-deploy:
      jobs:
        - build_and_test:
              filters:
                  tags:
                      only: /[0-9.]+(-(a|b|rc)[0-9]+)?/
              context:
                - DockerHub
        - deploy_snapshot:
              requires:
                  - build_and_test
              filters:
                  branches:
                      only: /((release|hotfix|support)/[0-9.]+(-(a|b|rc)[0-9]+)?|develop)/
              context:
                - DockerHub
        - deploy_release:
              requires:
                  - build_and_test
              filters:
                  tags:
                      only: /[0-9.]+(-(a|b|rc)[0-9]+)?/
                  branches:
                      ignore: /.*/
              context:
                - DockerHub